# Site settings
title: Abhay Gupta
baseurl:
url: "abgup.com"


# Build settings
kramdown:
  input: GFM
permalink: none

# Third-party services
# just leave blank to disable it
google_analytics:
disqus_shortname:

# All posts 
# NOTE: real posts need date in filename so use collections instead
collections:
  content:
    output: true
    permalink: /:name 
